# Generated by Django 4.2.4 on 2023-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='branch',
        ),
        migrations.AddField(
            model_name='task',
            name='commit',
            field=models.CharField(default='0bc33b41550102f7e8a3d5b9b99c11d352b7f629', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='repository',
            field=models.CharField(default='marla', max_length=255),
        ),
    ]
