# Generated by Django 4.2.4 on 2023-08-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outputs',
            field=models.JSONField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='script',
            field=models.CharField(default=''),
        ),
    ]
