version: '3'

services:
  app:
    build: .
    environment:
      - QUANDA_GITHUB_USER=${QUANDA_GITHUB_USER}
      - QUANDA_GITHUB_PAT=${QUANDA_GITHUB_PAT}
      - QUANDA_AWS_REGION=${QUANDA_AWS_REGION}
      - QUANDA_AWS_ACCESS_KEY_ID=${QUANDA_AWS_ACCESS_KEY_ID}
      - QUANDA_AWS_SECRET_ACCESS_KEY=${QUANDA_AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./quanda:/quanda
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=quandadb
      - POSTGRES_USER=quandauser
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  ui:
    build: ./ui
    volumes:
      - ./ui:/app
    ports:
      - "3000:3000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
