version: "3.8"

services:
  app:
    build:
      context: ./quanda
      dockerfile: Dockerfile.prod
    command: gunicorn quanda.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/quanda/quanda/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/quanda/quanda/staticfiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

volumes:
  postgres_data_prod:
  static_volume:
  acme:
  certs:
  html:
  vhost:
