# Generated by Django 4.2.4 on 2023-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(default='529e18f2-7ee9-4300-824f-1b75536a78ba', max_length=255, unique=True),
        ),
    ]
