# Generated by Django 4.2.4 on 2023-11-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default='6e57479a-faa9-4775-bb2e-3c8b042b0e08', max_length=255, unique=True),
        ),
    ]
