# Generated by Django 4.2.4 on 2023-12-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(default='19e94a88-676a-4d98-abeb-206fd5c09eb5', max_length=255, unique=True),
        ),
    ]
