# Generated by Django 4.2.4 on 2023-10-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='urgency',
        ),
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
