# Generated by Django 4.2.4 on 2023-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='frozen',
        ),
        migrations.RemoveField(
            model_name='item',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='item',
            name='system',
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(max_length=24),
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
