# Generated by Django 4.2.4 on 2023-10-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_urgency_item_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('relates_to', 'related_to'), ('supports', 'supports')], default='relates_to', max_length=16)),
                ('from_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_items', to='item.item')),
                ('to_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_items', to='item.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='links',
            field=models.ManyToManyField(through='item.ItemRelation', to='item.item'),
        ),
    ]
