# Generated by Django 4.2.4 on 2023-11-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itemrelation_item_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrelation',
            name='from_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_items', to='item.item'),
        ),
        migrations.AlterField(
            model_name='itemrelation',
            name='relation_type',
            field=models.CharField(choices=[('relates_to', 'relates_to'), ('supports', 'supports')], default='relates_to', max_length=16),
        ),
        migrations.AlterField(
            model_name='itemrelation',
            name='to_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_items', to='item.item'),
        ),
    ]
