# Use an official Node runtime as the parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application to the container
COPY . .

# Specify the command to run on container start
CMD ["npm", "start"]
